required-players: 1
countdown-seconds: 6
cuenta-aviso: 3
lobby-spawn:
  world: 'world'
  x: 163
  y: 9
  z: -125
  yaw: 90
  pitch: 0
arenas:
  0:
    sign:
      world: 'world'
      x: 165
      y: 9
      z: -123
    sign-exit:
      world: 'world'
      x: 147
      y: 5
      z: -86
    player-spawn:
      world: 'world'
      x: 153
      y: 4
      z: -89
      yaw: -90
      pitch: 0
  1:
    sign:
      world: 'world'
      x: 163
      y: 9
      z: -123
    sign-exit:
      world: 'world'
      x: 147
      y: 5
      z: -86
    player-spawn:
      world: 'world'
      x: 167
      y: 4
      z: -61
      yaw: -180
      pitch: 0
  2:
    sign:
      world: 'world'
      x: 161
      y: 9
      z: -123
    sign-exit:
      world: 'world'
      x: 147
      y: 5
      z: -86
    player-spawn:
      world: 'world'
      x: 167
      y: 4
      z: -69
      yaw: -180
      pitch: 0